### ISSUE TITLE
Is this project ready to be used?

### ISSUE THREAD

**Issue by fmontezuma** [stagemonitor/stagemonitor-kibana-6#1]
Is this project ready to be used?
Any reason it is not a branch of https://github.com/stagemonitor/stagemonitor-kibana ?
Is it possible to have releases ready to use as in https://github.com/stagemonitor/stagemonitor-kibana/releases ?

**Comment by liebhaeuser** [comment]
We are still working on this. As soon as the plugin is ready, there are going to be releases ready to use.

**Comment by fmontezuma** [comment]
Ok, thanks!
